apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment0
  labels:
    app: myapp0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp0
  template:
    metadata:
      labels:
        app: myapp0
    spec:
      containers:
      - name: myapp0
        image: le999/app1:1.0
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
---

apiVersion: v1
kind: Service
metadata:
  name: myapp0
spec:
  type: ClusterIP
  selector:
    app: myapp0 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: myapp0-lb
spec:
  selector:
    app: myapp0
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30001



