version: '2'

networks:
  docker-compose_k6:
    external: true

services:
  cli:
    container_name: cli
    image: loadimpact/k6:0.29.0
    stdin_open: true
    tty: true
    working_dir: /var/app
    user: ${CURRENT_UID}
    # command: ls
    volumes:
      - ../:/var/app/
    networks:
      - docker-compose_k6
    environment:
    - TARGET_HOST=172.17.0.1:3001     #localhost through docker network
    # - TARGET_HOST=192.168.99.100:30001  #minikube
